[font]
size = 50
size_increment = 2
max_size = 200
family = "'Roboto', sans-serif"

[screen]
padding.horizontal = 100
padding.vertical = 50
padding.increment = 10
padding.max_value = 250
hmargin.horizontal = 10
hmargin.vertical = 10
pmargin.horizontal = 50
pmargin.vertical = 50
scroll.speed = 10
scroll.speed_increment = 3
scroll.max_speed = 3
color= "white"
background= "black"
